branch-defaults:
  master:
    environment: customer-accounts-management-api-test
environment-defaults:
  customer-accounts-management-api-test:
    branch: null
    repository: null
global:
  application_name: customer-accounts-management-api
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Docker running on
    64bit Amazon Linux/2.12.2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: git
  workspace_type: Application
